services:
  - type: web
    name: Creative-Scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
      python -m playwright install-deps chromium
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /ping
