services:
  - type: web
    name: Creative-Scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: gunicorn main:app
    disk:
      name: playwright-cache
      mountPath: /opt/render/.cache/ms-playwright
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    healthCheckPath: /ping
