services:
  - type: web
    name: Creative-Scraper
    env: python
    plan: free
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
      apt-get install -y nodejs && \
      pip install -r requirements.txt && \
      python -m playwright install --with-deps chromium
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /ping.
